### ISSUE TITLE
Page Not Found Error on Refresh from Non-Home Pages

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/Library#5]
**Issue Description**
When navigating to a non-home page (e.g., book or contact page) within the Library website and then refreshing the page, a "Page Not Found" error is encountered. This issue does not occur when refreshing the home page.

**Steps to Reproduce**
1. Navigate to a non-home page (e.g., contact page) within the application.
2. Refresh the page using the browser's refresh button (F5 or Ctrl+R).

**Expected Behavior**
The page should refresh without encountering a "Page Not Found" error, maintaining the current page's content and state.

**Actual Behavior**
A "Page Not Found" error is displayed when refreshing from non-home pages, leading to a loss of context and content.

This issue impacts user experience and should be resolved to ensure consistent behavior across the application, regardless of the page being viewed.

If anyone has insights or a solution for this issue, please provide guidance. Thank you!

**Comment by rahmlad-aramide** [comment]
Hi @ajaynegi45 
I'll like to take this up, kindly assign me the issue
Thank you

**Comment by ajaynegi45** [comment]
**Assignee:** @rahmlad-aramide 

Hi @rahmlad-aramide,

Thank you for your willingness to address this issue. I've assigned it to you. Please feel free to start working on resolving the "Page Not Found" error when refreshing from non-home pages within the Library website.

If you have any questions or need further information to get started, don't hesitate to reach out. Your contributions are greatly appreciated!

**Comment by ajaynegi45** [comment]
@rahmlad-aramide,  are you currently working on this issue ?

**Comment by rahmlad-aramide** [comment]
Yes, I'm on it, thank you for asking and assigning it to me.

Abdrahman Oladimeji

**Comment by 31Pratishtha** [comment]
Hello, @rahmlad-aramide are you still working on this issue? If not I'd like to take this up.

**Comment by rahmlad-aramide** [comment]
Hi @31Pratishtha I've already resolved it, it just needs to be closed by the maintainer @ajaynegi45

**Comment by 31Pratishtha** [comment]
Oh okay.

**Comment by ajaynegi45** [comment]
> Oh okay.

You can work on another issues.
