### ISSUE TITLE
[bug]: All accordion cards expanded at same time

### ISSUE THREAD

**Issue by imSmaity** [ajaynegi45/Library#76]
**Describe the bug**
trying to expand any one of them but all accordion cards expanded same time.

**Expected behavior**
Expend only one of them which we clicked.

**Screen recorded video**

https://github.com/ajaynegi45/Library/assets/60940736/d89f72c8-7931-4561-8ae6-73b341ed3e2d

**Desktop** (please complete the following information):

OS: mac os
Browser [e.g. chrome]
Version [e.g. 221]

**Comment by imSmaity** [comment]
Can I work on that?

**Comment by ajaynegi45** [comment]
> OS: mac os

Yes, you can work on it

**Comment by ajaynegi45** [comment]
@imSmaity, Try check out our new project [Uttarakhand Culture Preservation Project](https://github.com/ajaynegi45/Uttarakhand-Culture-Preservation-Project)
