### ISSUE TITLE
Add 404 Page

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/Library#9]
**Issue Description**
As our Library website continues to grow, it's essential to provide a user-friendly experience, even when users land on non-existent pages or encounter broken links. To achieve this, we need to create a custom 404 error page that offers clear navigation options and helpful information when users reach a dead-end.

**Requirements**
1. **404 Page Design**: Design and implement a custom 404 error page that matches the overall look and feel of our website.

2. **User-Friendly Messaging**: Ensure the 404 page includes user-friendly messaging, informing visitors that the requested page couldn't be found. Provide guidance on how to navigate back to the homepage or explore other sections of the site.

3. **Responsive Design**: Make sure the 404 page is responsive and works well on various screen sizes and devices.

**Additional Information**
- You can create a new component for the 404 page and integrate it into our routing system.

This issue will contribute to a better user experience on our Library website by ensuring that visitors who encounter errors are guided effectively. If you have any questions or need further clarification, please don't hesitate to ask.

Thank you for your contribution!

**Comment by Honey2339** [comment]
Interesting, I would like to work on this.

**Comment by ajaynegi45** [comment]
> Interesting, I would like to work on this.

**Assignee:** @Honey2339 

Hi @Honey2339 ,

Thank you for showing interest in working on the "Add 404 Page" issue. I'm pleased to inform you that I have assigned this issue to you. We appreciate your willingness to contribute to our project, and we look forward to seeing your work on creating a user-friendly 404 page.

If you have any questions or need any assistance while working on this task, please feel free to reach out. Your efforts will significantly enhance the user experience on our Library website.

**Comment by Honey2339** [comment]
Review The PR Please
Thank You
